### ISSUE TITLE
[rmw_connext_cpp] Destructing node, specifically a default waitable, is slow (> 3s) for rmw_connext_cpp

### ISSUE THREAD

**Issue by brawner** [ros2/rclcpp#1250] opened 2020-07-31 18:59 UTC
The rclcpp unit tests take significantly longer for rmw_connext_cpp than other middleware implementations. 

Compare ConnextDDS unit tests with rclcpp (11 minutes)
http://build.ros2.org/view/Rci/job/Rci__nightly-connext_ubuntu_focal_amd64/32/testReport/rclcpp/

vs FastRTPS (1 min 30 s):
http://build.ros2.org/view/Rci/job/Rci__nightly-fastrtps_ubuntu_focal_amd64/34/testReport/rclcpp/

I've narrowed this down to the destruction of the rclcpp::Node, a call to destruct a waitable takes the vast majority of this time. I believe this is happening in AllocatorMemoryStrategy, but since it uses shared_ptrs, the actual destruct may be elsewhere.
If I put steady_clock measurements around [this line](https://github.com/ros2/rclcpp/blob/3b8c334d5dd5fddaf3fec03b34e6767a2fde3a78/rclcpp/include/rclcpp/strategies/allocator_memory_strategy.hpp#L90), or even if I iterate through the vector and call reset explicitly, there is one waitable that will consume significant amounts of time to delete. This isn't for all waitables, just one default one that I can't figure out where it's coming from.

**Comment by clalancette** [comment] 2020-08-20 17:26
This is essentially a duplicate of https://github.com/ros2/rmw_connext/issues/325 .  I'm going to close this out as a duplicate of that one, copying in your investigation here so it isn't lost.

**Closed by clalancette** 2020-08-20 17:26 UTC
