### ISSUE TITLE
👩‍🌾 New test failures: failed to create domain

### ISSUE THREAD

**Issue by chapulina** [ros2/rclcpp#1555] opened 2021-02-22 21:55 UTC
## Bug report

**Required Info:**

- Operating System:
  - macOS nightly CI (repeated)
- Installation type:
  - source
- Version or commit hash:
  - `master`
- DDS implementation:
  - default
- Client library (if applicable):
  -  `rclcpp`

#### Steps to reproduce issue

Run the same setup as macOS nightly CI.

#### Expected behavior

Test passes 100% of the time

#### Actual behavior

Some tests failed during the latest nightly, which had never failed before:

```
[ RUN      ] TestLoanedMessage.release
1613984918.563278 [180]   79839776: using network interface en0 (udp/192.168.1.120) selected arbitrarily from: en0, en1
1613984918.563388 [180]   79839776: ddsi_udp_create_conn: failed to bind to ANY:52401: address in use
[ERROR] [1613984918.563439845] [rmw_cyclonedds_cpp]: rmw_create_node: failed to create domain, error Error

>>> [rcutils|error_handling.c:108] rcutils_set_error_state()
This error state is being overwritten:

  'error not set, at /Users/osrf/jenkins-agent/workspace/nightly_osx_repeated/ws/src/ros2/rcl/rcl/src/rcl/node.c:262'

with this new error message:

  'rcl node's rmw handle is invalid, at /Users/osrf/jenkins-agent/workspace/nightly_osx_repeated/ws/src/ros2/rcl/rcl/src/rcl/node.c:414'

rcutils_reset_error() should be called after error handling to avoid this.
<<<
[ERROR] [1613984918.563489201] [rcl]: Failed to fini publisher for node: 1
unknown file: Failure
C++ exception with description "failed to initialize rcl node: rcl node's rmw handle is invalid, at /Users/osrf/jenkins-agent/workspace/nightly_osx_repeated/ws/src/ros2/rcl/rcl/src/rcl/node.c:414" thrown in the test body.
[  FAILED  ] TestLoanedMessage.release (3 ms)
```

```
01:08:54 45: [ RUN      ] TestNodeWithGlobalArgs.local_arguments_before_global
01:08:54 45: 1613984934.730056 [180]   79843201: using network interface en0 (udp/192.168.1.120) selected arbitrarily from: en0, en1
01:08:54 45: 1613984934.730232 [180]   79843201: ddsi_udp_create_conn: failed to bind to ANY:52400: address in use
01:08:54 45: [ERROR] [1613984934.730313580] [rmw_cyclonedds_cpp]: rmw_create_node: failed to create domain, error Error
01:08:54 45: 
01:08:54 45: >>> [rcutils|error_handling.c:108] rcutils_set_error_state()
01:08:54 45: This error state is being overwritten:
01:08:54 45: 
01:08:54 45:   'error not set, at /Users/osrf/jenkins-agent/workspace/nightly_osx_repeated/ws/src/ros2/rcl/rcl/src/rcl/node.c:262'
01:08:54 45: 
01:08:54 45: with this new error message:
01:08:54 45: 
01:08:54 45:   'rcl node's rmw handle is invalid, at /Users/osrf/jenkins-agent/workspace/nightly_osx_repeated/ws/src/ros2/rcl/rcl/src/rcl/node.c:414'
01:08:54 45: 
01:08:54 45: rcutils_reset_error() should be called after error handling to avoid this.
01:08:54 45: <<<
01:08:54 45: [ERROR] [1613984934.730421558] [rcl]: Failed to fini publisher for node: 1
01:08:54 45: unknown file: Failure
01:08:54 45: C++ exception with description "failed to initialize rcl node: rcl node's rmw handle is invalid, at /Users/osrf/jenkins-agent/workspace/nightly_osx_repeated/ws/src/ros2/rcl/rcl/src/rcl/node.c:414" thrown in the test body.
01:08:54 45: [  FAILED  ] TestNodeWithGlobalArgs.local_arguments_before_global (4 ms)
```

#### Additional information

These tests had been passing consistently until now, see their histories:

* https://ci.ros2.org/view/nightly/job/nightly_osx_repeated/2262/testReport/projectroot.test/rclcpp/test_loaned_message/history/
* https://ci.ros2.org/job/nightly_osx_repeated/2262/testReport/junit/rclcpp/TestNodeWithGlobalArgs/local_arguments_before_global/history/

---

https://github.com/osrf/buildfarmer/issues/161

**Comment by wjwwood** [comment] 2021-02-22 22:49
I think this is a duplicate of https://github.com/ros2/rmw_cyclonedds/issues/281, which started out here, but I moved to rmw cyclone because it's not something rclcpp can control most likely. Though there's on going discussion there. Either way this is a duplicate I think.

**Closed by wjwwood** 2021-02-22 22:49 UTC
Labels: CycloneDDS, macOS, tests
