### ISSUE TITLE
Action Client: Feeback callback called after cancel

### ISSUE THREAD

**Issue by jmachowinski** [ros2/rclcpp#2265] opened 2023-08-04 11:30 UTC
## Bug report

- Operating System:
  - Ubuntu 22.04
- Installation type:
  - binaries
- Version or commit hash:
  - iron
- DDS implementation:
  - cyclone
- Client library (if applicable):
  - rclcpp_action

#### Steps to reproduce issue
Use mutlithreaded spinners

Set up a server that sends a lot of feedback

Set up a client
Cancel the goal

#### Expected behavior
After async_cancel goal the feedback callback should not be called any more

#### Actual behavior
The feedback callback is called after cancel

#### Additional information
This leads to segfaults for us, as we delete the objects associated with the 
ClientGoalHandle once its cancelled.

Also node, we can't check the status of the goal in the callback, as it deadlocks (see https://github.com/ros2/rclcpp/issues/2243). 

#### Implementation considerations
For a solution I would propose to to check the status of the handle in https://github.com/ros2/rclcpp/blob/ea29c142af320bff06f957ec9172caf3a4aff41a/rclcpp_action/include/rclcpp_action/client_goal_handle_impl.hpp#L163
and not call the feedback callback if the status of the is not STATUS_EXECUTING

**Comment by CursedRock17** [comment] 2023-08-06 01:18
So I set this up and can see what you're saying, but just as a clarifier where are you cancelling the goal in the code. I have an example set up just like #2243, where I cancel the goal before sending as well as after sending and it just throws an exception and terminates
```
exception of type rclcpp_action::exceptions::UnknownGoalHandleError: Goal handle is not known to this client.
```
which is the expected behavior. The real question is how much should this be down to the user to not: cancel the goal, then try to send it?

**Comment by fujitatomoya** [comment] 2023-08-06 01:50
@jmachowinski i am not really sure what the problem here, could you elaborate a bit?

> After async_cancel goal the feedback callback should not be called any more

what if the cancel request is rejected? we cannot assume cancel request is always accepted by server.

> The feedback callback is called after cancel

i think server publishes the feedback until the cancel request has been accepted on server side.

**Comment by jmachowinski** [comment] 2023-08-07 12:52
@CursedRock17 I got a huge system were multiple goals are send to one server, and either the client or the server cancels  them depending on various conditions. 

The crashes I am seeing seem to originate from two race conditions:
- Feedback, status goal cancel and result are all transported on different channels within rcl. Therefore there is no guaranteed order in which they arrive. 
- There is a race condition between the drop of the shared pointer the the goal handle and the callbacks.

As a solution for now I would propose a new API call drop_handle() in the client:

```c++
void drop_handle(typename GoalHandle::SharedPtr goal_handle)
{
    std::lock_guard<std::mutex> lock(goal_handles_mutex_);
    auto it = goal_handles_.find(goal_handle->get_goal_id());
    if (it == goal_handles_.end()) {
      throw exceptions::UnknownGoalHandleError();
    }
   goal_handles_.erase(it);
}
``` 
Using this, as a user, I could safely drop the handle, and afterwards be sure that I don't get any callbacks any more.

**Comment by jmachowinski** [comment] 2023-08-07 13:12
@fujitatomoya My main problem is that I don't have a safe way to drop a client handle, I am not interested in any more.

I also just took a look at the tutorial (https://docs.ros.org/en/iron/Tutorials/Intermediate/Writing-an-Action-Server-Client/Cpp.html) and now I am totally confused. In the tutorial the future with the goal handle is not saved. Why is it working at all ?

**Comment by fujitatomoya** [comment] 2023-08-07 17:23
@jmachowinski thanks for iterating and sharing.

> My main problem is that I don't have a safe way to drop a client handle, I am not interested in any more.

I was expecting that feedback callback will not be called once the client drops that goal handle in the application.

https://github.com/ros2/rclcpp/blob/e2965831d51e9be03470cb07f8721012afcade9b/rclcpp_action/include/rclcpp_action/client.hpp#L645-L650

> The feedback callback is called after cancel

feedback topic would be published on the server side after cancel acceptance? this is just an acceptance of cancel request, so there will be canceling process in the server side. during this process, server would publish the feedback, and the client would need the final feedback until it is actually canceled? if the client is not interested in this goal, it can just drop the handler not to receive the feedback?

> This leads to segfaults for us, as we delete the objects associated with the ClientGoalHandle once its cancelled.

i may be mistaken... back to the original problem, what callstack are you receiving?

**Comment by fujitatomoya** [comment] 2023-08-07 18:29
> I also just took a look at the tutorial (https://docs.ros.org/en/iron/Tutorials/Intermediate/Writing-an-Action-Server-Client/Cpp.html) and now I am totally confused. In the tutorial the future with the goal handle is not saved. Why is it working at all ?

you are right, that does confuse me as well. i will be checking on this. thanks for pointing this out.

**Comment by jmachowinski** [comment] 2023-08-08 09:50
I created an example that triggers the bug : https://github.com/jmachowinski/rclcppActionDeadlock branch callAfterDrop

In the output you can see the effect: E.g. :
```
[INFO] [1691487734.551874717] [DeadlockClient]: Setting new goal for ID 29 ptr is 0x7f9a44002260
[INFO] [1691487734.552407302] [DeadlockClient]: TrajectoryExecution29: Goal accepted ptr is 0x7f9a44002260
[INFO] [1691487734.552998487] [DeadlockClient]: TrajectoryExecution 29: action result ABORTED ptr is 0x7f9a50001910
[INFO] [1691487734.651881737] [DeadlockClient]: Setting new goal for ID 22 ptr is 0x7f9a60002d20
[INFO] [1691487734.652383102] [DeadlockClient]: TrajectoryExecution22: Goal accepted ptr is 0x7f9a60002d20
[INFO] [1691487734.652770914] [DeadlockClient]: TrajectoryExecution 22: action result ABORTED ptr is 0x7f9a68002390
.
.
.
[INFO] [1691487736.951888299] [DeadlockClient]: Setting new goal for ID 29 ptr is 0x55b501dc3c70
[ERROR] [1691487736.952026479] [DeadlockClient]: stateChangeFeedback for ID 29 called but handle was dropped ptr is 0x7f9a44002260
[ERROR] [1691487736.952121288] [DeadlockClient]: stateChangeFeedback for ID 29 called with invalid handle ptr is 0x7f9a44002260
``` 
From the address of the ptr, one can see that its a call after the drop of the handle, and this should not happen.

**Comment by jmachowinski** [comment] 2023-08-08 10:07
And for explanation of what I think of what is going on is a race condition between line 
https://github.com/ros2/rclcpp/blob/e2965831d51e9be03470cb07f8721012afcade9b/rclcpp_action/include/rclcpp_action/client.hpp#L653

and line 
https://github.com/ros2/rclcpp/blob/e2965831d51e9be03470cb07f8721012afcade9b/rclcpp_action/include/rclcpp_action/client.hpp#L662

The code checks, if the handle is still valid, and afterwards calls the feedback callback. But exactly in this time frame, a second thread may jump in and drop the handle.

**Comment by jmachowinski** [comment] 2023-08-08 16:27
@fujitatomoya 
> you are right, that does confuse me as well. i will be checking on this. thanks for pointing this out.

I think I just found the answer : https://github.com/ros2/rclcpp/blob/e2965831d51e9be03470cb07f8721012afcade9b/rclcpp_action/include/rclcpp_action/client.hpp#L715

This creates a copy of the goalHandle and keeps the whole  thing alive until the result cb was called.

**Comment by CursedRock17** [comment] 2023-08-14 14:58
For the first issue with saving of a value all we should have to do is capture `goal_handle` by reference in order to control the actual object to call `goal_handle->set_result(wrapped_result);`

As for the `DropHandle` function you created, where would the user put that that get full usage, because it seems like the intention is that the user will drop the handle, before requesting for another feedback message. Would this still be able to cause a data race/missing goal_handle as a thread could be [executing](https://github.com/ros2/rclcpp/blob/e2965831d51e9be03470cb07f8721012afcade9b/rclcpp_action/include/rclcpp_action/client.hpp#L662)?

If we wanted to generally fix this, we would have to lock the goal_handles while the feedback is occurring or wait until the feedback is complete, before we allow the goal handle to be erased.

**Comment by CursedRock17** [comment] 2023-08-14 16:57
Hold on, there is already a TODO, for almost exactly what you proposed with the `DropHandle` function in the [client.hpp](https://github.com/ros2/rclcpp/blob/e2965831d51e9be03470cb07f8721012afcade9b/rclcpp_action/include/rclcpp_action/client.hpp#L464) file:
```
// TODO(jacobperron): Encapsulate into it's own function and
    //                    consider exposing an option to disable this cleanup
    // To prevent the list from growing out of control, forget about any goals
    // with no more user references
    {
      std::lock_guard<std::mutex> guard(goal_handles_mutex_);
      auto goal_handle_it = goal_handles_.begin();
      while (goal_handle_it != goal_handles_.end()) {
        if (!goal_handle_it->second.lock()) {
          RCLCPP_DEBUG(
            this->get_logger(),
            "Dropping weak reference to goal handle during send_goal()");
          goal_handle_it = goal_handles_.erase(goal_handle_it);
        } else {
          ++goal_handle_it;
        }
      }
    }

```

The TODO was added in 2020 in pull request #1122

Then, in a related issue there is an explanation for why the feedback is called after the cancel
> My understanding is that even if the goal is terminated clients should still be able to get the result

**Comment by jmachowinski** [comment] 2023-08-15 09:21
I have patches ready that fix this. I am currently in vacation until next week. Then I can post them for feedback/review.

**Comment by fujitatomoya** [comment] 2023-08-16 20:11
@jmachowinski 
CC: @CursedRock17 

I am still not sure what the problem is...

> The code checks, if the handle is still valid, and afterwards calls the feedback callback. But exactly in this time frame, a second thread may jump in and drop the handle.

it is protected by mutex lock, https://github.com/ros2/rclcpp/blob/65f0b70d4aa4d1a3b8dc4c08aae26151ca00ca55/rclcpp_action/include/rclcpp_action/client.hpp#L640 ?

and it locks on https://github.com/ros2/rclcpp/blob/65f0b70d4aa4d1a3b8dc4c08aae26151ca00ca55/rclcpp_action/include/rclcpp_action/client.hpp#L651 before callback?

**Comment by CursedRock17** [comment] 2023-08-19 18:32
Yeah, that's the only part that confuses me about this whole thing, would there be a place where the lock_guard goes out of scope, so that the guard would release temporarily?

**Comment by jmachowinski** [comment] 2023-08-21 07:59
The problem is not the lock itself, but the usage of weak pointers / shared pointers.

Thread 2:
```c++
     class Foo {
         GoalHandle::SharedPtr handle;
         void callback();

         //calls async_cancel_goal()
         void cancel_goal();
     };
     std::unique_ptr<Foo> bar = std::make_unique<Foo>();

     // Acquire lock, and release at end, note the weak pointer is still valid here
     bar->cancel_goal();
```

Thread 1:
```c++
    // weak ptr is still valid therefore we pass here
    typename GoalHandle::SharedPtr goal_handle = goal_handles_[goal_id].lock();
    // Forget about the goal if there are no more user references
    if (!goal_handle) {
      RCLCPP_DEBUG(
        this->get_logger(),
        "Dropping weak reference to goal handle during feedback callback");
      goal_handles_.erase(goal_id);
      return;
    }
```
Thread 2:
```c++
     bar.reset();
``` 
Now the handle is dropped, and the object the callbacks are pointing too is invalid.

Thread1 :
```c++
    auto feedback = std::make_shared<Feedback>();
    *feedback = feedback_message->feedback;
    // FAIL Call to invalid memory
    goal_handle->call_feedback_callback(goal_handle, feedback);
```

**Comment by jmachowinski** [comment] 2023-08-21 11:32
@fujitatomoya @CursedRock17  I created a merge request for the patches, can you have a look at them ?

**Closed** 2024-04-15 17:05 UTC
