### ISSUE TITLE
test_executors test failing on Windows debug

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/rclcpp#1282] opened 2020-08-20 17:08 UTC
See https://ci.ros2.org/view/nightly/job/nightly_win_deb/1712/testReport/junit/projectroot/test/test_executors/ for the first failing build.

It seems this regressions was introduced in #1270.

**Comment by brawner** [comment] 2020-08-20 17:43
Thanks for bringing this to my attention. This might be related to what I was discussing in #1230, but it looks like it's more repeatable than what I was discovering and more targeted to individual tests.

**Comment by brawner** [comment] 2020-08-20 21:14
Having trouble reproducing on bare-metal. While my docker image is building, I'm also running this CI job:

[![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=11969)](https://ci.ros2.org/job/ci_windows/11969/)

**Comment by brawner** [comment] 2020-08-25 18:35
I'm still working on this, but I have to take a break to address other things. I'll come back to this soon.

**Comment by chapulina** [comment] 2020-11-06 22:38
This test has been failing consistently for a long time. I'm suggesting disabling it in https://github.com/ros2/rclcpp/pull/1443

**Comment by brawner** [comment] 2020-11-24 01:25
This was resolved by #1404 (rolling) and #1401 (foxy).

**Closed by brawner** 2020-11-24 01:25 UTC
Labels: Windows, bug, tests
