### ISSUE TITLE
Component Container process has died ROS2 galactic RCLCPP

### ISSUE THREAD

**Issue by NamanMM** [ros2/rclcpp#2368] opened 2023-11-13 17:20 UTC
Hello everyone,

I have been getting the following error (In the callback function of the node) resulting in the crash. It is sporadic and slightly tricky to reproduce but here is the error message:

1699879254.0570445 [ERROR] [component_container-1]: process has died [pid 597648, exit code -11, cmd '/opt/ros/galactic/lib/rclcpp_components/component_container --ros-args -r __node:=crop_spec_container -r __ns:=/'].

I have gone through the log files and nothing pops out immediately; the node seemed to be running well till this crash happens.

Any pointers or suggestion will be appreciated.
Thank you in advance.

**Comment by clalancette** [comment] 2023-11-13 17:37
Galactic is now End-of-Life.  Can you try this out on Humble, Iron, or Rolling to see if you still have the same problem?

**Comment by Apurv354** [comment] 2023-11-14 01:56
Try adding [gdb](https://www.sourceware.org/gdb/) to debug.

**Comment by NamanMM** [comment] 2023-11-14 09:58
I did and I am attaching the screenshot (Sorry I am not able to find the text where I copied the error). 
![gdb](https://github.com/ros2/rclcpp/assets/128400956/3fc835eb-33a0-46d1-9fd5-905949a071a3)

**Comment by Zard-C** [comment] 2023-11-15 18:35
From gdb: in frame 4, it was caused by std::vector<T>::push_back(T const &),  you can enter this frame and check the msg. My understanding of this issue is: `std::vector` is not thread-safe in the standard library, which means that simultaneous access to the same std::vector instance from multiple threads without appropriate synchronization mechanisms can lead to data races and memory corruption.

**Comment by Zard-C** [comment] 2023-11-20 16:41
any update? 😄  @NamanMM

**Comment by mjcarroll** [comment] 2023-11-20 17:00
What you are seeing is very unlikely an issue with the component container, but rather an issue with your node implementation.

While the component container (and components in general) can get you higher performance via intraprocess pub/sub, it comes with the downside of making a fault in a single node take down the entire container.

What I would suggest is that you separate the nodes that are in your component container and run them in separate process to make the system more robust.  You can then being to debug/diagnose the faulty node.

Looking at the traceback, I would be inclined to agree with @Zard-C that this is you trying to append to a non-thread-safe structure from multiple threads.

I'm going to close this out.  If you can establish that there is a bug in the component container, feel free to re-open.

**Closed by mjcarroll** 2023-11-20 17:00 UTC
Labels: more-information-needed

**Comment by NamanMM** [comment] 2023-11-20 19:45
@Zard-C @mjcarroll Thank you guys. I did find an issue in how the vector was being used across threads - I have fixed it. I will monitor it for some time; happy to keep this closed.
