### ISSUE TITLE
Node namespace is not always added to the topic name

### ISSUE THREAD

**Issue by EduPonz** [ros2/rclcpp#1767] opened 2021-09-08 13:17 UTC
## Bug report

**Required Info:**

- Operating System:
  - Any
- Installation type:
  - Any
- Version or commit hash:
  - ROS 2 Galactic
- DDS implementation:
  - Any
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

Maybe this is a design feature, but I could not find any documentation on it, nor am I sure where to look for it TBH. The issue is as follows: if a publisher is created with a topic starting with `/`, the node's namespace is not prepended to the topic name. That is:

| User topic name | Node namespace | Final topic name |
|-|-|-|
| `chatter` | `test` | `/test/chatter` |
| `chatter` | `/test` | `/test/chatter` |
| `/chatter` | `test` | `/chatter` |
| `/chatter` | `/test` | `/chatter` |

This is originated in https://github.com/ros2/rclcpp/blob/master/rclcpp/include/rclcpp/node_impl.hpp#L62-L68, where the name space is only prepended if the topic name does not start with `/` or `~`. This makes it a bit more difficult to predict the final topic name, as the namespace is not always there. I first notice it will investigating ros2/rmw_fastrtps#554, for which I have submitted ros2/rmw_fastrtps#557, but I want to be sure whether this is how it's meant to be or if it's a bug in rclcpp.

Steps to reproduced can be found in [here](https://github.com/ros2/rmw_fastrtps/issues/554#issuecomment-915052822), just add some namespace to the node, name the topic `/chatter` when creating the publisher, and then run `ros2 topic list`

#### Expected behavior

I would have expected for the namespace to always be part of the topic name, but maybe I'm missing something.

#### Actual behavior

The namespace is only part of the topic name if the topic name does not start with `/` or `~`

**Comment by clalancette** [comment] 2021-09-08 13:44
This is by design; see http://design.ros2.org/articles/static_remapping.html .

In short, the idea is that you might have topics like `/tf` or `/clock` that you always want in the "global" namespace.  Imagine that you have a camera node that also subscribes to `/tf`.  Now imagine that you want to run two instances of the camera node, one for the left camera, and one for the right.  You launch the first one in namespace `left` and the second one in namespace `right`.  You still want both nodes to subscribe to global `/tf`, but you want everything else to be namespaced `left` or `right` as appropriate.

I'm going to close this out, but feel free to re-open if this doesn't answer your question.

**Closed by clalancette** 2021-09-08 13:44 UTC
